<img style="float: left; margin: 30px 15px 15px 15px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFzQj91sOlkeDFkg5HDbjtR4QJYmLXkfMNig&usqp=CAU" width="400" height="500" /> 
    
    
### <font color='navy'> Simulación matemática. 

**Nombres:** Sindy Citlali Sánchez Ponce, Carolina Anidsel Casillas García.

**Fecha:** 14 de septiembre del 2022.

**Expediente** : **721658, 740286**.
    
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github**: https://github.com/CarolinaCasillas/T3SindySanchez_CarolinaCasillas

# Tarea 3

### 1. Otro problema de transporte

La empresa Carbones de oriente debe ingresar a la empresa un requerimiento mínimo diario de carbón de $5000$ kg de carbón de alto volátil, $4000$ kg de medio volátil y $3000$ kg de bajo volátil para su debido proceso y trasformación. 

La entrada de estos se da en la siguiente tabla (los valores corresponden a un viaje en kg): 

-|Alto volátil|Medio volátil|Bajo volátil
:----|----|----|----
Mina sur|80|70|65
Mina norte|60|50|40
Mina central|40|30|20

El costo del trasporte de un viaje de cada mina es de 2500 dólares, 1500 dólares y 900 dólares, respectivamente. ¿Cuántos viajes de cada mina se deben recibir a diario para suplir los requerimientos mínimos y generar el menor costo de transporte? 

Para simplificar la notación use las siguientes variables: 

+ $x_1:$ Cantidad de viajes de la mina sur  
+ $x_2:$ Cantidad de viajes de la mina norte  
+ $x_3:$ Cantidad de viajes de la mina central  


El objetivo consiste consiste en plantear el problema de programación lineal que permita satisfacer los requerimientos de la empresa Carbones de oriente y resolverlo con `linprog`.

### 2. 
Una empresa de muebles rústicos fabrica entre muchos otros productos cinco tipos de sillas A, B, C, D Y E, las cuales se venden a precio de $1100$, $1300$, $1200$, $980$ y $1010$ pesos cada una y respectivamente. 

Las sillas pasan por cinco procesos: corte, ensamblado, lijado, pintado y sellado, para lo cual se dispone máximo de $17$, $11$, $15$, $12$ y $14$ horas respectivamente a la semana para dedicar a estas operaciones a estos productos.

Los requerimientos, en horas, para cada una de las sillas está dado en la siguiente tabla:

-|Corte|Ensamblado|Lijado|Pintado|Sellado
:----|----|----|----|----|----
Silla A|3|1|3|1|1
Silla B|2|3|2|2|3
Silla C|5|2|2|3|1
Silla D|2|4|1|1|2
Silla E|1|0|2|2|3

¿Cuántas sillas de cada tipo se deben fabricar para suplir los requerimientos de disponibiladas semanal y generar la mayor utilidad en ventas? 

Para simplificar la notación use las siguientes variables: 

+ $x_A:$ Cantidad de sillas tipo A 
+ $x_B:$ Cantidad de sillas tipo B 
+ $x_C:$ Cantidad de sillas tipo C 
+ $x_D:$ Cantidad de sillas tipo D  
+ $x_E:$ Cantidad de sillas tipo E


El objetivo consiste consiste en plantear el problemade programación lineal que permita satisfacer los requerimientos de la empresa empresa de muebles y resolverlo con `linprog`.


Código de solución estudiante 1

#### Solución - Ejercicio 1

Sean:
+ $x_1:$ Cantidad de viajes de la mina sur  
+ $x_2:$ Cantidad de viajes de la mina norte  
+ $x_3:$ Cantidad de viajes de la mina central 

Lo que se quiere es minimizar es el costo de transporte $2500x_1+1500x_2+900x_3$.

Restricciones:
1. Requerimiento mínimo diario de $5000$ kg de carbón de alto volátil: $80x_1+60x_2+40x_3\geq 5000$   
2. Requerimiento mínimo diario de $4000$ kg de carbón medio volátil: $70x_1+50x_2+30x_3\geq 4000$   
3. Requerimiento mínimo diario de $3000$ kg de carbón bajo volátil: $65x_1+40x_2+20x_3\geq 3000$   

Finalmente, el problema puede ser expresado en la forma explicada como:
\begin{equation}
\begin{array}{ll}
\min_{x_1,x_2,x_3} & 2500x_1+1500x_2+900x_3 \\
\text{s. a. }  & -80x_1-60x_2-40x_3\leq -5000 \\
               & -70x_1-50x_2-30x_3\leq -4000 \\
               & -65x_1-40x_2-20x_3\leq -3000,
\end{array}
\end{equation}

o, eqivalentemente 
\begin{equation}
\begin{array}{ll}
\min_{\boldsymbol{x}} & \boldsymbol{c}^\top\boldsymbol{x} \\
\text{s. a. }        & \boldsymbol{A}_{eq}\boldsymbol{x}=\boldsymbol{b}_{eq} \\
                     & \boldsymbol{A}\boldsymbol{x}\leq\boldsymbol{b},
\end{array}
\end{equation}
con
- $\boldsymbol{c}=\left[2500 \quad 1500 \quad 900\right]^\top$,
- $\boldsymbol{A}=\left[\begin{array}{cc}-80 & -60 & -40 \\ -70 & -50 & -30 \\ -65 & -40 & -20\end{array}\right]$, y
- $\boldsymbol{b}=\left[-5000 \quad -4000 \quad -3000\right]^\top$.

In [5]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy.optimize as opt

In [6]:
c = np.array([2500, 1500, 900])
A = np.array([[-80, -60, -40],
             [-70, -50, -30],
             [-65, -40, -20]])
b = np.array([-5000,-4000,-3000])

In [7]:
c,b,A

(array([2500, 1500,  900]),
 array([-5000, -4000, -3000]),
 array([[-80, -60, -40],
        [-70, -50, -30],
        [-65, -40, -20]]))

In [8]:
sol_viajes = opt.linprog(c,A,b, method='simplex')

In [9]:
sol_viajes

     con: array([], dtype=float64)
     fun: 119999.99999999999
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([ 0.00000000e+00, -4.54747351e-13,  0.00000000e+00])
  status: 0
 success: True
       x: array([ 0., 50., 50.])

In [10]:
x = sol_viajes.x
x

array([ 0., 50., 50.])

**Conclusión**
- Para minimizar el costo de transporte la mina sur no debe hacer ningún viaje, mina norte debe hacer $50$ viajes y la mina central debe hacer $50$ viajes.
- El costo total de transporte será de $120,000$ dólares.

#### Solución - Ejercicio 2

Sean:
+ $x_A:$ Cantidad de sillas tipo A 
+ $x_B:$ Cantidad de sillas tipo B 
+ $x_C:$ Cantidad de sillas tipo C 
+ $x_D:$ Cantidad de sillas tipo D  
+ $x_E:$ Cantidad de sillas tipo E

Lo que se quiere es maximizar son las utilidades en ventas $1100x_A+1300x_B+1200x_C+980x_D+1010x_E$.

Restricciones:
1. Disponibilidad de máximo de 17 horas semanales para corte: $3x_A+2x_B+5x_C+2x_D+1x_E\leq 17$   
2. Disponibilidad de máximo de 11 horas semanales para ensamblado: $1x_A+3x_B+2x_C+4x_D\leq 11$   
3. Disponibilidad de máximo de 15 horas semanales para lijado: $3x_A+2x_B+2x_C+1x_D+2x_E\leq 15$    
4. Disponibilidad de máximo de 12 horas semanales para pintado: $1x_A+2x_B+3x_C+1x_D+2x_E\leq 12$    
5. Disponibilidad de máximo de 14 horas semanales para ensamblado: $1x_A+3x_B+1x_C+2x_D+3x_E\leq 14$    

Finalmente, el problema puede ser expresado en la forma explicada como:
\begin{equation}
\begin{array}{ll}
\min_{x_A,x_B,x_C,x_D,x_E} & -1100x_A-1300x_B-1200x_C-980x_D-1010x_E \\
\text{s. a. }  & 3x_A+2x_B+5x_C+2x_D+1x_E\leq 17 \\
               & 1x_A+3x_B+2x_C+4x_D\leq 11 \\
               & 3x_A+2x_B+2x_C+1x_D+2x_E\leq 15 \\
               & 1x_A+2x_B+3x_C+1x_D+2x_E\leq 12 \\
               & 1x_A+3x_B+1x_C+2x_D+3x_E\leq 14,
\end{array}
\end{equation}

o, eqivalentemente 
\begin{equation}
\begin{array}{ll}
\min_{\boldsymbol{x}} & \boldsymbol{c}^\top\boldsymbol{x} \\
\text{s. a. }        & \boldsymbol{A}_{eq}\boldsymbol{x}=\boldsymbol{b}_{eq} \\
                     & \boldsymbol{A}\boldsymbol{x}\leq\boldsymbol{b},
\end{array}
\end{equation}
con
- $\boldsymbol{c}=\left[-1100 \quad -1300 \quad -1200 \quad -980 \quad -1010 \right]^\top$,
- $\boldsymbol{A}=\left[\begin{array}{cc}3 & 2 & 5 & 2 & 1 \\ 1 & 3 & 2 & 4 & 0 \\ 3 & 2 & 2 & 1 & 2 \\ 1 & 2 & 3 & 1 & 2 \\ 1 & 3 & 1 & 2 & 3\end{array}\right]$, y
- $\boldsymbol{b}=\left[17 \quad 11 \quad 15 \quad 12 \quad 14 \right]^\top$.

In [11]:
c = np.array([-1100, -1300, -1200, -980, -1010])
A = np.array([[3, 2, 5, 2, 1],
             [1, 3, 2, 4, 0],
             [3, 2, 2, 1, 2],
             [1, 2, 3, 1, 2],
             [1, 3, 1, 2, 3]])
b = np.array([17, 11, 15, 12, 14])

In [12]:
c,b,A

(array([-1100, -1300, -1200,  -980, -1010]),
 array([17, 11, 15, 12, 14]),
 array([[3, 2, 5, 2, 1],
        [1, 3, 2, 4, 0],
        [3, 2, 2, 1, 2],
        [1, 2, 3, 1, 2],
        [1, 3, 1, 2, 3]]))

In [13]:
sol_sillas = opt.linprog(c,A,b,method='simplex')

In [14]:
sol_sillas

     con: array([], dtype=float64)
     fun: -7700.0
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([0.00000000e+00, 0.00000000e+00, 3.55271368e-15, 0.00000000e+00,
       0.00000000e+00])
  status: 0
 success: True
       x: array([2., 1., 1., 1., 2.])

**Conclusión**
- Para maximizar las utilidades se deben hacer semanalmente $2$ sillas tipo A, $1$ silla tipo B, $1$ silla tipo C, $1$ silla tipo D y $2$ silla tipo D.
- La mayor utilidad obtenida será de $7,700$ pesos.

Código de solución estudiante 2

In [31]:
#Importar numpy y el módulo optimize de la librería scipy
import numpy as np 
import scipy.optimize as opt

In [32]:
#Ejercicio 1
# Crear las matrices para resolver el problema
c = np.array([2500,1500,900])
b = np.array([-5000,-4000,-3000])
A = np.array([[-80,-60,-40],
             [-70,-50,-30],
             [-65,-40,-20]])

In [33]:
c,b,A

(array([2500, 1500,  900]),
 array([-5000, -4000, -3000]),
 array([[-80, -60, -40],
        [-70, -50, -30],
        [-65, -40, -20]]))

In [34]:
sol_ej1 = opt.linprog(c,A,b,method='simplex')

In [35]:
sol_ej1

     con: array([], dtype=float64)
     fun: 119999.99999999999
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([ 0.00000000e+00, -4.54747351e-13,  0.00000000e+00])
  status: 0
 success: True
       x: array([ 0., 50., 50.])

In [36]:
#Ejercicio 2
# Crear las matrices para resolver el problema
c = np.array([-1100,-1300,-1200.,-980,-1010])
b = np.array([17,11,15,12,14])
A = np.array([[3,2,5,2,1],
             [1,3,2,4,0],
             [3,2,2,1,2],
             [1,2,3,1,2],
             [1,3,1,2,3]])

In [37]:
c,b,A

(array([-1100., -1300., -1200.,  -980., -1010.]),
 array([17, 11, 15, 12, 14]),
 array([[3, 2, 5, 2, 1],
        [1, 3, 2, 4, 0],
        [3, 2, 2, 1, 2],
        [1, 2, 3, 1, 2],
        [1, 3, 1, 2, 3]]))

In [38]:
sol_ej2 = opt.linprog(c, A, b)

In [39]:
sol_ej2

     con: array([], dtype=float64)
     fun: -7699.999999956599
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([7.63478170e-11, 4.03233003e-12, 9.50599599e-11, 1.70071957e-10,
       7.64099894e-11])
  status: 0
 success: True
       x: array([2., 1., 1., 1., 2.])

### Respuesta planteada en el ejercicio usando (markdown)





 #### Estudiante 2
 ##### Ejercicio 1
 Nuestra función de utilidad es:
 
 $  2500x_{1} +1500 x_{2} + 900x_{3} $
 
 Restricciones: 
 
1. Se debe cumplir con al menos **5000 kg** de carbón **Alto volatil**: $80x_{1} + 60x_{2} + 40x_{3} \geq 5000$
2. Se debe cumplir con al menos **4000 kg** de carbón **Medio volatil**: $70x_{1} + 50x_{2} + 30x_{3} \geq 4000$
3. Se debe cumplir con al menos **3000 kg** de carbón **Bajo volatil**:$65x_{1} + 40x_{2} + 20x_{3} \geq 3000$
 
Cambiamos el signo de las ecuaciones para cambiar la igualdad.

 $\boldsymbol{c}=\left[2500 \quad 1500 \quad 900\right]^\top$,
 
 $\boldsymbol{A}=\left[\begin{array}{cc} -80 & -60 & -40 \\ -70 & -50 & -30 \\ -65 & -40 & -20 \end{array}\right]$, y
 
 $\boldsymbol{b}=\left[-5000 \quad -4000\quad -3000\right]^\top$.
 
Como resultado se obtiene un costo mínimo de $120000 con **50** viajes de la **Mina norte** y **50** viajes de la **Mina central**. El algoritmo arroja que no se deben realizar viajes de la Mina Sur.
 
 ##### Ejercicio 2
 
 Nuestra función de utilidad es:
 
 $ 1100 x_{a} +1300 x_{b} + 1200x_{c} +980x_{d} + 1010x_{e}$
 
 Restricciones: 
 
1. El tiempo de **Corte** debe ser menor a **17**: $3x_{a} + 2x_{b} + 5x_{c} + 2x_{d} + 1x_{e} \leq 17$
2. El tiempo de **Ensamblado** debe ser menor a **11**: $1x_{a} + 3x_{b} + 2x_{c} + 4x_{d} + 0x_{e} \leq 11$
3. El tiempo de **Lijado** debe ser menor a **15**: $3x_{a} + 2x_{b} + 2x_{c} + 1x_{d} + 2x_{e} \leq 15$
4. El tiempo de **Pintado** debe ser menor a **12**: $1x_{a} + 2x_{b} + 3x_{c} + 1x_{d} + 2x_{e} \leq 12$
5. El tiempo de **Sellado** debe ser menor a **14**: $1x_{a} + 3x_{b} + 1x_{c} + 2x_{d} + 3x_{e} \leq 14$
 
Como es un problema donde buscamos maximizar los beneficios, multiplicamos c por -1.

 $\boldsymbol{c}=\left[-1100 \quad -1300 \quad -1200 \quad -980 \quad -1010\right]^\top$,
 
 $\boldsymbol{A}=\left[\begin{array}{cc} 3 & 2 & 5 & 2 &1 \\ 1 & 3 & 2 & 4 & 0 \\ 3 & 2 & 2 & 1 & 2 \\ 1 & 2 & 3 & 1 & 2 \\ 1 & 3 & 1 & 2 & 3\end{array}\right]$, y
 
 $\boldsymbol{b}=\left[17 \quad 11\quad 15 \quad 12 \quad 14\right]^\top$.
 
Como resultado se obtiene una utilidad máxima de $7700 con la elaboracion de **2** sillas A, **1** silla B, **1** silla C, **1** silla D y **2** sillas D.